# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://python:3.9.4-slim
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup PYTHONPATH
      run: |
        echo "PYTHONPATH=/__w/volpy/volpy" >> $GITHUB_ENV
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pipenv bandit 
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Code scanner - bandit
      run: |
        bandit -r ./volpy
    - name: Test with pytest
      env:
          PYTHON_PATH: ${{ secrets.PYTHONPATH }}
      run: |
        cd tests
        pytest -v
